# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('poster', models.FileField(blank=True, upload_to=b'', verbose_name='\u041f\u043e\u0441\u0442\u0435\u0440 \u0444\u0438\u043b\u044c\u043c\u0430')),
                ('title_film', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435:')),
                ('year_pub', models.DateField(verbose_name='\u0412\u044b\u0445\u043e\u0434 \u0432 \u043f\u0440\u043e\u043a\u0430\u0442:')),
                ('genre', models.CharField(max_length=255, verbose_name='\u0416\u0430\u043d\u0440:')),
                ('producer', models.CharField(max_length=150, verbose_name='\u041f\u0440\u043e\u0434\u044e\u0441\u0435\u0440:')),
                ('budget', models.PositiveIntegerField(verbose_name='\u0411\u044e\u0434\u0436\u0435\u0442:')),
                ('fees', models.PositiveIntegerField(verbose_name='\u0421\u0431\u043e\u0440\u044b:')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c, \u043c\u0438\u043d.:')),
                ('content', models.TextField(blank=True, max_length=10000, verbose_name='\u0421\u044e\u0436\u0435\u0442:')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442:')),
                ('birth_date', models.DateField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f:')),
                ('avatar', models.FileField(upload_to=b'', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
