# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models
from films.models import Film


def forward(apps, schema_editor):
    producer_model = apps.get_model('films', 'Producer')
    producers = Film.objects.values_list('producer', flat=True).distinct()
    producers = [producer_model(full_name=p) for p in producers]
    producer_model.objects.bulk_create(producers)


def backward(apps, schema_editor):
    producer_model = apps.get_model('films', 'Producer')
    producer_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('films', '0008_auto_20171024_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
            ],
        ),
        migrations.RunPython(forward, backward)
    ]
