# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    producer_model = apps.get_model('films', 'Producer')
    film_model = apps.get_model('films', 'Film')
    producers = producer_model.objects.all()
    producer_mapping = {p.full_name: p.id for p in producers}

    films = film_model.objects.all()

    producer_film_mapping = {f.id: f.producer for f in films}

    films = film_model.objects.all()
    for f in films:
        producer = producer_film_mapping.get(f.id, None)
        if producer is None:
            continue

        producer_id = producer_mapping.get(producer, None)
        if producer_id is None:
            continue

        f.producer_id = producer_id

        f.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('films', '0009_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Продюсер', 'verbose_name_plural': 'Продюсеры'},
        ),
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Producer',
                                    verbose_name='Продюсер:'),
        )
    ]
