# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20171107_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.genre', verbose_name='Жанр:'),
        ),
    ]
