# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20171107_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genre',
            new_name='Genres',
        ),
    ]
