# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_auto_20171115_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
