# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_auto_20171116_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
