# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name')),
                ('password', models.CharField(max_length=200, verbose_name='пароль')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Населенный пункт:')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения:')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар:')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
    ]
